WebApplication1/Models/HerbatyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace WebApplication1.Models
{
    public class HerbatyModel
    {
        // model do bazy danych
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public string Cena { get; set; }
        public string Zdjęcie { get; set; }

    }

    public class HerbataDBContext : DbContext
    {
        public DbSet<HerbatyModel> Herbaty { get; set; }
    }
}

WebApplication1/Controllers/HerbatyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HerbatyController : Controller
    {
        private HerbataDBContext db = new HerbataDBContext();

        // GET: Herbaty
        public ActionResult Index()
        {
            return View(db.Herbaty.ToList());
        }

        // GET: Herbaty/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HerbatyModel herbatyModel = db.Herbaty.Find(id);
            if (herbatyModel == null)
            {
                return HttpNotFound();
            }
            return View(herbatyModel);
        }

        // GET: Herbaty/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Herbaty/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nazwa,Cena,Zdjęcie")] HerbatyModel herbatyModel)
        {
            if (ModelState.IsValid)
            {
                db.Herbaty.Add(herbatyModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(herbatyModel);
        }

        // GET: Herbaty/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HerbatyModel herbatyModel = db.Herbaty.Find(id);
            if (herbatyModel == null)
            {
                return HttpNotFound();
            }
            return View(herbatyModel);
        }

        // POST: Herbaty/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nazwa,Cena,Zdjęcie")] HerbatyModel herbatyModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(herbatyModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(herbatyModel);
        }

        // GET: Herbaty/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HerbatyModel herbatyModel = db.Herbaty.Find(id);
            if (herbatyModel == null)
            {
                return HttpNotFound();
            }
            return View(herbatyModel);
        }

        // POST: Herbaty/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HerbatyModel herbatyModel = db.Herbaty.Find(id);
            db.Herbaty.Remove(herbatyModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Views/Herbaty/Create.cshtml
@model WebApplication1.Models.HerbatyModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HerbatyModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zdjęcie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zdjęcie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zdjęcie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Herbaty/Delete.cshtml
@model WebApplication1.Models.HerbatyModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HerbatyModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zdjęcie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zdjęcie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Herbaty/Details.cshtml
@model WebApplication1.Models.HerbatyModel

@{
    ViewBag.Title = "Szczegóły";
}

<h2>Szczegóły</h2>

<div>
    <h4>HerbatyModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zdjęcie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zdjęcie)
            <img src="@Html.DisplayFor(model => model.Zdjęcie)">
        </dd>

    </dl>
    <a style="text-align:center; background-color: greenyellow; color: black; font-size: 25px;"> dodaj do koszyka @Html.DisplayFor(model => model.Nazwa)</a>
</div>
<p>
    @Html.ActionLink("Wróć do listy", "Index")
</p>

WebApplication1/Views/Herbaty/Edit.cshtml
@model WebApplication1.Models.HerbatyModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HerbatyModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zdjęcie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zdjęcie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zdjęcie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Herbaty/Index.cshtml
@model IEnumerable<WebApplication1.Models.HerbatyModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cena)
        </th>
    <!--   <th>
            @Html.DisplayNameFor(model => model.Zdjęcie)
        </th> -->
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cena)
        </td>
        <!--<td>
            @Html.DisplayFor(modelItem => item.Zdjęcie)
            <img src="@Html.DisplayFor(modelItem => item.Zdjęcie)">
        </td>-->
        <td>
            <!--@Html.ActionLink("Edit", "Edit", new { id=item.ID }) | -->
     @Html.ActionLink("Szczegóły", "Details", new { id=item.ID }) 
    <!-- @Html.ActionLink("Delete", "Delete", new { id=item.ID }) -->
        </td>
    </tr>
}

</table>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nazwa aplikacji", "Index", "Herbaty", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Herbaty")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Moja aplikacja ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>